services:
  db:
    image: postgres:latest
    container_name: gestone_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 46310045415dD@
      POSTGRES_DB: gestone_db
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: